import json
from pathlib import Path
from typing import Dict, Any
from .bilingual_legal import BilingualDeed
from .merkle_anchor import MerkleAuditPackage


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Legal Testament & Attestation Deed — Vaani Vasiyat</title>
<style>
  body {{
    font-family: 'Times New Roman', serif;
    margin: 40px;
    color: #111;
    line-height: 1.6;
    background-color: #fafafa;
  }}
  .deed-container {{
    max-width: 850px;
    margin: 0 auto;
    background: #fff;
    padding: 50px 60px;
    border: 2px solid #333;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
  }}
  .header {{
    text-align: center;
    border-bottom: 2px double #333;
    padding-bottom: 20px;
    margin-bottom: 30px;
  }}
  .header h1 {{
    margin: 0;
    font-size: 24px;
    letter-spacing: 2px;
    text-transform: uppercase;
  }}
  .header .sub {{
    margin-top: 6px;
    font-size: 14px;
    color: #555;
    font-style: italic;
  }}
  .merkle-banner {{
    background: #f0f7ff;
    border: 1px solid #c2dbff;
    padding: 12px 16px;
    margin-bottom: 30px;
    font-family: monospace;
    font-size: 12px;
  }}
  .section-title {{
    font-weight: bold;
    font-size: 16px;
    margin-top: 25px;
    margin-bottom: 8px;
    text-transform: uppercase;
    border-bottom: 1px solid #ccc;
    padding-bottom: 4px;
  }}
  .bilingual-block {{
    display: flex;
    gap: 20px;
    margin-bottom: 20px;
  }}
  .bilingual-col {{
    flex: 1;
    font-size: 14px;
    text-align: justify;
  }}
  .indic-col {{
    background: #fdfdfd;
    padding: 10px;
    border-left: 3px solid #6366f1;
  }}
  .sign-area {{
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid #333;
  }}
  .sign-grid {{
    display: flex;
    justify-content: space-between;
    margin-top: 30px;
  }}
  .sign-box {{
    width: 45%;
    border: 1px dashed #777;
    padding: 15px;
    min-height: 90px;
    text-align: center;
  }}
  .thumb-mark-box {{
    border: 1px solid #aaa;
    width: 90px;
    height: 100px;
    margin: 10px auto;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 11px;
    color: #888;
  }}
  .footer {{
    margin-top: 50px;
    border-top: 1px solid #ddd;
    padding-top: 15px;
    font-size: 11px;
    color: #666;
    text-align: center;
  }}
</style>
</head>
<body>

<div class="deed-container">
  <div class="header">
    <h1>Last Will and Testament</h1>
    <div class="sub">अंतिम वसीयतनामा एवं उत्तराधिकार विलेख</div>
    <div class="sub">Executed in accordance with Section 63 of the Indian Succession Act, 1925</div>
  </div>

  <div class="merkle-banner">
    <strong>CRYPTOGRAPHIC PROVENANCE ANCHOR (BSA SEC 63 / IEA 65B):</strong><br>
    Package ID: {package_id}<br>
    Merkle Root: <strong>{merkle_root}</strong><br>
    Voice Intake SHA-256: {audio_hash}<br>
    Attestation Timestamp: {timestamp}
  </div>

  <div class="section-title">I. English Statutory Will Deed</div>
  <div style="white-space: pre-line; font-size: 14px; margin-bottom: 30px;">
{english_text}
  </div>

  <div class="section-title">II. Regional Language Translated Deed (क्षेत्रीय भाषा प्रतिलेख)</div>
  <div class="indic-col" style="white-space: pre-line; font-size: 14px; margin-bottom: 30px;">
{indic_text}
  </div>

  <div class="sign-area">
    <div class="section-title">III. Execution & Attestation Under Section 63 ISA</div>
    
    <div class="sign-grid">
      <div class="sign-box">
        <strong>Testator Signature / Mark</strong>
        <div class="thumb-mark-box">Left Thumb Impression</div>
        <p style="font-size: 12px; margin-top: 5px;">(Signed in the physical presence of both witnesses)</p>
      </div>
      <div class="sign-box">
        <strong>Witness 1 Attestation</strong>
        <p style="font-size: 12px; text-align: left; margin-top: 10px;">
          Name: {w1_name}<br>
          ID: {w1_id}<br>
          Sign: ____________________
        </p>
      </div>
    </div>

    <div class="sign-grid" style="margin-top: 15px;">
      <div class="sign-box" style="visibility: hidden;"></div>
      <div class="sign-box">
        <strong>Witness 2 Attestation</strong>
        <p style="font-size: 12px; text-align: left; margin-top: 10px;">
          Name: {w2_name}<br>
          ID: {w2_id}<br>
          Sign: ____________________
        </p>
      </div>
    </div>
  </div>

  <div class="footer">
    Generated by Vaani Vasiyat (Sarvam AI Indic Platform). Ready for presentation to the Sub-Registrar Office.<br>
    Cryptographic Manifest binds Audio Recording, Saaras ASR, Mayura Legal Translation, and Witness Attestations.
  </div>
</div>

</body>
</html>
"""


def export_testamentary_deed(
    deed: BilingualDeed,
    merkle_pkg: MerkleAuditPackage,
    output_dir: Path,
    base_name: str = "vaani_vasiyat_deed",
) -> Dict[str, Path]:
    """Generate printable HTML deed, JSON cryptographic manifest, and audit summary."""
    output_dir.mkdir(parents=True, exist_ok=True)

    w1 = merkle_pkg.witnesses[0] if len(merkle_pkg.witnesses) > 0 else None
    w2 = merkle_pkg.witnesses[1] if len(merkle_pkg.witnesses) > 1 else None

    audio_leaf = next((l for l in merkle_pkg.leaves if "Voice Recording" in l.label), None)
    audio_hash = audio_leaf.hash_value if audio_leaf else "N/A"

    html_content = HTML_TEMPLATE.format(
        package_id=merkle_pkg.package_id,
        merkle_root=merkle_pkg.merkle_root,
        audio_hash=audio_hash,
        timestamp=merkle_pkg.created_at_utc,
        english_text=deed.english_draft,
        indic_text=deed.indic_draft,
        w1_name=w1.full_name if w1 else "____________________",
        w1_id=f"{w1.id_type} {w1.id_number_masked}" if w1 else "____________________",
        w2_name=w2.full_name if w2 else "____________________",
        w2_id=f"{w2.id_type} {w2.id_number_masked}" if w2 else "____________________",
    )

    html_file = output_dir / f"{base_name}.html"
    with open(html_file, "w", encoding="utf-8") as f:
        f.write(html_content)

    manifest_file = output_dir / f"{base_name}_manifest.json"
    with open(manifest_file, "w", encoding="utf-8") as f:
        f.write(merkle_pkg.model_dump_json(indent=2))

    return {
        "html_deed": html_file,
        "manifest": manifest_file,
    }
